// Code generated by MockGen. DO NOT EDIT.
// Source: accrual_calculator_interface.go

// Package mocksaccrualcalculator is a generated GoMock package.
package mocksaccrualcalculator

import (
	context "context"
	reflect "reflect"

	dto "github.com/Raime-34/gophermart.git/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockaccrualCalculator is a mock of accrualCalculator interface.
type MockaccrualCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockaccrualCalculatorMockRecorder
}

// MockaccrualCalculatorMockRecorder is the mock recorder for MockaccrualCalculator.
type MockaccrualCalculatorMockRecorder struct {
	mock *MockaccrualCalculator
}

// NewMockaccrualCalculator creates a new mock instance.
func NewMockaccrualCalculator(ctrl *gomock.Controller) *MockaccrualCalculator {
	mock := &MockaccrualCalculator{ctrl: ctrl}
	mock.recorder = &MockaccrualCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccrualCalculator) EXPECT() *MockaccrualCalculatorMockRecorder {
	return m.recorder
}

// AddToMonitoring mocks base method.
func (m *MockaccrualCalculator) AddToMonitoring(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToMonitoring", arg0, arg1)
}

// AddToMonitoring indicates an expected call of AddToMonitoring.
func (mr *MockaccrualCalculatorMockRecorder) AddToMonitoring(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToMonitoring", reflect.TypeOf((*MockaccrualCalculator)(nil).AddToMonitoring), arg0, arg1)
}

// StartMonitoring mocks base method.
func (m *MockaccrualCalculator) StartMonitoring(arg0 context.Context) <-chan *dto.AccrualCalculatorDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMonitoring", arg0)
	ret0, _ := ret[0].(<-chan *dto.AccrualCalculatorDTO)
	return ret0
}

// StartMonitoring indicates an expected call of StartMonitoring.
func (mr *MockaccrualCalculatorMockRecorder) StartMonitoring(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMonitoring", reflect.TypeOf((*MockaccrualCalculator)(nil).StartMonitoring), arg0)
}
