postgres:
	docker run --name postgres -p 5432:5432 -e POSTGRESQL_USERNAME=dbuser -e POSTGRESQL_PASSWORD=password123 -d postgresql:14

createdb:
	docker exec -it postgres createdb --username=dbuser --owner=dbuser simple_bank

drobdb:
	docker exec -it postgres dropdb simple_bank

migrateup:
	migrate -path ./internal/db/shcema -database "postgres://127.0.0.1/gofermart?sslmode=disable&user=dbuser&password=password123" up

migratedown:
	migrate -path ./internal/db/shcema -database "postgres://127.0.0.1/gofermart?sslmode=disable&user=dbuser&password=password123" up


.PHONY: postgres createdb drobdb migrateup migratedown
