CREATE TABLE gophermart.orders (
    id SERIAL PRIMARY KEY,
    number TEXT NOT NULL,
    status TEXT NOT NULL,
    accrual BIGINT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
