// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"time"
)

// Balance defines model for Balance.
type Balance struct {
	Current   float64 `json:"current"`
	Withdrawn float64 `json:"withdrawn"`
}

// Error defines model for Error.
type Error struct {
	// Message Error message
	Message string `json:"message"`
}

// Order defines model for Order.
type Order struct {
	Accrual    *float64  `json:"accrual,omitempty"`
	Number     string    `json:"number"`
	Status     string    `json:"status"`
	UploadedAt time.Time `json:"uploaded_at"`
}

// User defines model for User.
type User struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Withdrawal defines model for Withdrawal.
type Withdrawal struct {
	Order       string     `json:"order"`
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	Sum         float64    `json:"sum"`
}

// UploadOrderTextBody defines parameters for UploadOrder.
type UploadOrderTextBody = string

// WithdrawalRequestJSONRequestBody defines body for WithdrawalRequest for application/json ContentType.
type WithdrawalRequestJSONRequestBody = Withdrawal

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = User

// UploadOrderTextRequestBody defines body for UploadOrder for text/plain ContentType.
type UploadOrderTextRequestBody = UploadOrderTextBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = User
