// Code generated by MockGen. DO NOT EDIT.
// Source: cookie_handler_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/Raime-34/gophermart.git/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockcookieHandlerInterface is a mock of cookieHandlerInterface interface.
type MockcookieHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockcookieHandlerInterfaceMockRecorder
}

// MockcookieHandlerInterfaceMockRecorder is the mock recorder for MockcookieHandlerInterface.
type MockcookieHandlerInterfaceMockRecorder struct {
	mock *MockcookieHandlerInterface
}

// NewMockcookieHandlerInterface creates a new mock instance.
func NewMockcookieHandlerInterface(ctrl *gomock.Controller) *MockcookieHandlerInterface {
	mock := &MockcookieHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockcookieHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcookieHandlerInterface) EXPECT() *MockcookieHandlerInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockcookieHandlerInterface) Get(arg0 string) (*dto.UserData, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*dto.UserData)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcookieHandlerInterfaceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockcookieHandlerInterface)(nil).Get), arg0)
}

// Set mocks base method.
func (m *MockcookieHandlerInterface) Set(arg0 string, arg1 *dto.UserData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1)
}

// Set indicates an expected call of Set.
func (mr *MockcookieHandlerInterfaceMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockcookieHandlerInterface)(nil).Set), arg0, arg1)
}
