// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/Raime-34/gophermart.git/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockgophermartInterface is a mock of gophermartInterface interface.
type MockgophermartInterface struct {
	ctrl     *gomock.Controller
	recorder *MockgophermartInterfaceMockRecorder
}

// MockgophermartInterfaceMockRecorder is the mock recorder for MockgophermartInterface.
type MockgophermartInterfaceMockRecorder struct {
	mock *MockgophermartInterface
}

// NewMockgophermartInterface creates a new mock instance.
func NewMockgophermartInterface(ctrl *gomock.Controller) *MockgophermartInterface {
	mock := &MockgophermartInterface{ctrl: ctrl}
	mock.recorder = &MockgophermartInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgophermartInterface) EXPECT() *MockgophermartInterfaceMockRecorder {
	return m.recorder
}

// GetUserBalance mocks base method.
func (m *MockgophermartInterface) GetUserBalance(arg0 context.Context) (*dto.BalanceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", arg0)
	ret0, _ := ret[0].(*dto.BalanceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockgophermartInterfaceMockRecorder) GetUserBalance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockgophermartInterface)(nil).GetUserBalance), arg0)
}

// GetUserOrders mocks base method.
func (m *MockgophermartInterface) GetUserOrders(ctx context.Context) ([]*dto.GetOrdersInfoResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx)
	ret0, _ := ret[0].([]*dto.GetOrdersInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockgophermartInterfaceMockRecorder) GetUserOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockgophermartInterface)(nil).GetUserOrders), ctx)
}

// GetWithdraws mocks base method.
func (m *MockgophermartInterface) GetWithdraws(arg0 context.Context) ([]*dto.WithdrawInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdraws", arg0)
	ret0, _ := ret[0].([]*dto.WithdrawInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdraws indicates an expected call of GetWithdraws.
func (mr *MockgophermartInterfaceMockRecorder) GetWithdraws(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdraws", reflect.TypeOf((*MockgophermartInterface)(nil).GetWithdraws), arg0)
}

// InsertOrder mocks base method.
func (m *MockgophermartInterface) InsertOrder(ctx context.Context, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrder", ctx, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrder indicates an expected call of InsertOrder.
func (mr *MockgophermartInterfaceMockRecorder) InsertOrder(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrder", reflect.TypeOf((*MockgophermartInterface)(nil).InsertOrder), ctx, orderNumber)
}

// LoginUser mocks base method.
func (m *MockgophermartInterface) LoginUser(arg0 context.Context, arg1 dto.UserCredential) (*dto.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0, arg1)
	ret0, _ := ret[0].(*dto.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockgophermartInterfaceMockRecorder) LoginUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockgophermartInterface)(nil).LoginUser), arg0, arg1)
}

// ProcessWithdraw mocks base method.
func (m *MockgophermartInterface) ProcessWithdraw(arg0 context.Context, arg1 dto.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWithdraw", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWithdraw indicates an expected call of ProcessWithdraw.
func (mr *MockgophermartInterfaceMockRecorder) ProcessWithdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWithdraw", reflect.TypeOf((*MockgophermartInterface)(nil).ProcessWithdraw), arg0, arg1)
}

// RegisterUser mocks base method.
func (m *MockgophermartInterface) RegisterUser(arg0 context.Context, arg1 dto.UserCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockgophermartInterfaceMockRecorder) RegisterUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockgophermartInterface)(nil).RegisterUser), arg0, arg1)
}
