// Code generated by MockGen. DO NOT EDIT.
// Source: repositories_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/Raime-34/gophermart.git/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockrepositoriesInt is a mock of repositoriesInt interface.
type MockrepositoriesInt struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoriesIntMockRecorder
}

// MockrepositoriesIntMockRecorder is the mock recorder for MockrepositoriesInt.
type MockrepositoriesIntMockRecorder struct {
	mock *MockrepositoriesInt
}

// NewMockrepositoriesInt creates a new mock instance.
func NewMockrepositoriesInt(ctrl *gomock.Controller) *MockrepositoriesInt {
	mock := &MockrepositoriesInt{ctrl: ctrl}
	mock.recorder = &MockrepositoriesIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepositoriesInt) EXPECT() *MockrepositoriesIntMockRecorder {
	return m.recorder
}

// GetOrders mocks base method.
func (m *MockrepositoriesInt) GetOrders(ctx context.Context) ([]*dto.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx)
	ret0, _ := ret[0].([]*dto.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockrepositoriesIntMockRecorder) GetOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockrepositoriesInt)(nil).GetOrders), ctx)
}

// GetUser mocks base method.
func (m *MockrepositoriesInt) GetUser(ctx context.Context, userInfo dto.UserCredential) (*dto.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userInfo)
	ret0, _ := ret[0].(*dto.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockrepositoriesIntMockRecorder) GetUser(ctx, userInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockrepositoriesInt)(nil).GetUser), ctx, userInfo)
}

// GetWithdraws mocks base method.
func (m *MockrepositoriesInt) GetWithdraws(ctx context.Context) ([]*dto.WithdrawInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdraws", ctx)
	ret0, _ := ret[0].([]*dto.WithdrawInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdraws indicates an expected call of GetWithdraws.
func (mr *MockrepositoriesIntMockRecorder) GetWithdraws(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdraws", reflect.TypeOf((*MockrepositoriesInt)(nil).GetWithdraws), ctx)
}

// RegisterOrder mocks base method.
func (m *MockrepositoriesInt) RegisterOrder(ctx context.Context, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOrder", ctx, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterOrder indicates an expected call of RegisterOrder.
func (mr *MockrepositoriesIntMockRecorder) RegisterOrder(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOrder", reflect.TypeOf((*MockrepositoriesInt)(nil).RegisterOrder), ctx, orderNumber)
}

// RegisterUser mocks base method.
func (m *MockrepositoriesInt) RegisterUser(ctx context.Context, userInfo dto.UserCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, userInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockrepositoriesIntMockRecorder) RegisterUser(ctx, userInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockrepositoriesInt)(nil).RegisterUser), ctx, userInfo)
}

// RegisterWithdraw mocks base method.
func (m *MockrepositoriesInt) RegisterWithdraw(ctx context.Context, req dto.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterWithdraw", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterWithdraw indicates an expected call of RegisterWithdraw.
func (mr *MockrepositoriesIntMockRecorder) RegisterWithdraw(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWithdraw", reflect.TypeOf((*MockrepositoriesInt)(nil).RegisterWithdraw), ctx, req)
}

// UpdateOrder mocks base method.
func (m *MockrepositoriesInt) UpdateOrder(ctx context.Context, state dto.AccrualCalculatorDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockrepositoriesIntMockRecorder) UpdateOrder(ctx, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockrepositoriesInt)(nil).UpdateOrder), ctx, state)
}
