// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anon-d/gophermarket/internal/worker (interfaces: WorkerRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository_test.go -package=worker github.com/anon-d/gophermarket/internal/worker WorkerRepository
//

// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	reflect "reflect"

	repository "github.com/anon-d/gophermarket/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkerRepository is a mock of WorkerRepository interface.
type MockWorkerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkerRepositoryMockRecorder is the mock recorder for MockWorkerRepository.
type MockWorkerRepositoryMockRecorder struct {
	mock *MockWorkerRepository
}

// NewMockWorkerRepository creates a new mock instance.
func NewMockWorkerRepository(ctrl *gomock.Controller) *MockWorkerRepository {
	mock := &MockWorkerRepository{ctrl: ctrl}
	mock.recorder = &MockWorkerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRepository) EXPECT() *MockWorkerRepositoryMockRecorder {
	return m.recorder
}

// GetOrdersForProcessing mocks base method.
func (m *MockWorkerRepository) GetOrdersForProcessing(ctx context.Context) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersForProcessing", ctx)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersForProcessing indicates an expected call of GetOrdersForProcessing.
func (mr *MockWorkerRepositoryMockRecorder) GetOrdersForProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersForProcessing", reflect.TypeOf((*MockWorkerRepository)(nil).GetOrdersForProcessing), ctx)
}

// UpdateOrderStatus mocks base method.
func (m *MockWorkerRepository) UpdateOrderStatus(ctx context.Context, orderNumber, status string, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockWorkerRepositoryMockRecorder) UpdateOrderStatus(ctx, orderNumber, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockWorkerRepository)(nil).UpdateOrderStatus), ctx, orderNumber, status, accrual)
}
