### Registration User
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "login": "user1",
  "password": "password1"
}

### Login User
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "user",
  "password": "password"
}

### Login User WRONG
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "user1",
  "password": "password1"
}

### POST Order num
POST http://localhost:8080/api/user/orders
Cookie: gophermart_session=MTY3MDcwMDcyMXxEdi1CQkFFQ180SUFBUkFCRUFBQUh2LUNBQUVHYzNSeWFXNW5EQWtBQjNWelpYSmZhV1FEYVc1MEJBSUFBZz09fMn_z1ZYjMp56XPiofehatgrRTHDSQpgCm4mXyXzr0p_
Content-Type: text/plain

12345678903

